FROM openjdk:17-jdk-alpine
LABEL authors="Le_Nin"
COPY target/currency-exchange-service-0.0.12-SNAPSHOT.jar currency-exchange-service-0.0.12-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/currency-exchange-service-0.0.12-SNAPSHOT.jar"]